Fomka-Web-App/fomka-web/Controllers/ForumController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace fomka_web.Controllers
{
    public class ForumController : Controller
    {
        // GET: Forum
        public ActionResult Index()
        {
            return View();
        }
    }
}

Fomka-Web-App/fomka-web/Controllers/NewsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace fomka_web.Controllers
{
    public class NewsController : Controller
    {
        // GET: News
        public ActionResult Index()
        {
            return View();
        }
    }
}

Fomka-Web-App/fomka-web/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - My ASP.NET Application</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    <style>
        .d-inline {
        }
    </style>
</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @Html.ActionLink("Віртуальна лабораторія ПІ", "Index", "Home", new { area = "" }, new { @class = "navbar-brand" })
            </div>
            <div class="navbar-collapse collapse" style="display: inline-block !important;">
                <ul class="nav navbar-nav">
                    <li>@Html.ActionLink("Головна", "Index", "Home")</li>
                    <li>@Html.ActionLink("Новини", "Index", "News")</li>
                    <li>@Html.ActionLink("Форум", "Index", "Forum")</li>
                </ul>
            </div>
            <div class="navbar-collapse collapse" style="display: inline-block !important; float: right;">
                <ul class="nav navbar-nav">
                    @if (HttpContext.Current.User.Identity.IsAuthenticated)
                    {
                        <li><a>Привіт, @HttpContext.Current.User.Identity.Name</a></li>
                    }
                    else
                    {
                        <li>@Html.ActionLink("Увійти", "Login", "Home")</li>
                    }
                    <li>@Html.ActionLink("Вийти", "Logout", "Home")</li>
                </ul>
            </div>
        </div>
    </div>
    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year - NULP. This project is totally not hardcoded</p>
        </footer>
    </div>

    
    @RenderSection("scripts", required: false)
</body>
</html>