Fomka-Web-App/fomka-web/Controllers/TasksController.cs
using fomka_web.DAL;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using fomka_web.Attributes;
using fomka_web.BL;
using fomka_web.Models;
using fomka_web.Domain;
using static fomka_web.Attributes.RoleAuthorizeAttribute;

namespace fomka_web.Controllers
{
    public class TasksController : BaseController
    {
        private TaskVm vm = new TaskVm();
        private MainRepo dbRepo = new MainRepo();
        // GET: Tasks
        public ActionResult Index()
        {
            return View();
        }

        [HttpGet]
        public ActionResult Open(string taskId, string mode)
        {
            string blocks = null;
            var selection = "";
            if (mode == "open") {
                vm.Task = dbRepo.GeTaskById(Convert.ToInt32(taskId));
                vm.SequenceOfBlocks = BlockGenerator.RandomizeBlocks(BlockGenerator.Code2Blocks(vm.Task.Standard.StandardFile, vm.Task.DifficultyLevelId.Value));
                vm.SelectedBlocks = new List<BlockOfCode>();
                vm.blocks = BlockGenerator.GetOrder(vm.SequenceOfBlocks);
                vm.selection = "";
                return View(vm);
            }
            else
            {
                if (Request.Cookies["blocks"] != null)
                {
                    selection = Uri.UnescapeDataString(Request.Cookies["selection"].Value);
                    blocks = Uri.UnescapeDataString(Request.Cookies["blocks"].Value);
                }

                vm.Task = dbRepo.GeTaskById(Convert.ToInt32(taskId));

                var codeBlocks = BlockGenerator.Code2Blocks(vm.Task.Standard.StandardFile, vm.Task.DifficultyLevelId.Value);
                vm.SelectedBlocks = BlockGenerator.OrderBlocks(codeBlocks, selection);
                vm.SequenceOfBlocks = BlockGenerator.SetSelected(BlockGenerator.OrderBlocks(codeBlocks, blocks), vm.SelectedBlocks);
                vm.selection = selection;
                vm.blocks = blocks;

                return View(vm);
            }
        }

        public ActionResult Select(string taskId)
        {
            return RedirectToAction("Open",new{ taskId = taskId});
        }

        [RoleAuthorize(UserType = AppUserType.Lecturer)]
        public ActionResult Edit(string taskId)
        {
            vm.Task = dbRepo.GeTaskById(Convert.ToInt32(taskId));
            var difficultyLevels = dbRepo.GetDifficultyLevels();
            vm.DifficultyLevels = difficultyLevels.Select(d => new SelectListItem() {Text = d.Title, Value = d.Id.ToString()}).ToList();
            var programmingLanguages = dbRepo.GetLanguages();
            vm.ProgrammingLanguages = programmingLanguages.Select(d => new SelectListItem() { Text = d.Title, Value = d.Id.ToString() }).ToList();
            return View(vm);
        }

        [Authorize]
        public ActionResult Submit(TaskVm vm)
        {
            var userName = GeLoginInfo().Username;
            var userId = dbRepo.GetUserByUsername(userName).Id;
            vm.Task = dbRepo.GeTaskById(vm.Task.Id);
            if (vm.Task.Marks.Select(m=>m.UserId==userId).Count() == 0)
            {
                string blocks = null;
                var selection = "";
                if (Request.Cookies["blocks"] != null)
                {
                    selection = Uri.UnescapeDataString(Request.Cookies["selection"].Value);
                    blocks = Uri.UnescapeDataString(Request.Cookies["blocks"].Value);
                }

                var codeBlocks = BlockGenerator.Code2Blocks(vm.Task.Standard.StandardFile, vm.Task.DifficultyLevelId.Value);
                vm.SelectedBlocks = BlockGenerator.OrderBlocks(codeBlocks, selection);
                vm.SequenceOfBlocks =
                    BlockGenerator.SetSelected(BlockGenerator.OrderBlocks(codeBlocks, blocks), vm.SelectedBlocks);
                vm.selection = selection;
                vm.blocks = blocks;

                var answer = BlockGenerator.AnswerCorrectInPercent(vm.SelectedBlocks, vm.SequenceOfBlocks);
                vm.Answer = "Завдання успішно здано. Ваша оцінка: " + answer.ToString("F3");
                
                dbRepo.SaveMark(taskId: vm.Task.Id, mark: answer, userId: userId);
            }
            else
            {
                vm.Answer = "Ви вже виконали дане завдання";
            }

            return View(vm);
        }

        [HttpPost]
        [ValidateInput(false)]
        public ActionResult EditTask(TaskVm vm)
        {
            dbRepo.SaveTask(vm.Task);
            return RedirectToAction("Index","Home", new { id = vm.Task.ModuleId });
        }

        [RoleAuthorize(UserType = AppUserType.Lecturer)]
        public ActionResult Add()
        {
            vm.Task = new Task();
            var difficultyLevels = dbRepo.GetDifficultyLevels();
            vm.DifficultyLevels = difficultyLevels.Select(d => new SelectListItem() { Text = d.Title, Value = d.Id.ToString() }).ToList();
            var programmingLanguages = dbRepo.GetLanguages();
            vm.ProgrammingLanguages = programmingLanguages.Select(d => new SelectListItem() { Text = d.Title, Value = d.Id.ToString() }).ToList();
            var modules = dbRepo.GetModules();
            vm.Modules = dbRepo
                .GetModules()
                .Select(m => new SelectListItem() { Text = m.Title, Value = m.Id.ToString() }).ToList();

            return View(vm);
        }

        [HttpPost]
        [ValidateInput(false)]
        public ActionResult AddTask(TaskVm vm)
        {
            dbRepo.SaveTask(vm.Task);
            return RedirectToAction("Index", "Home", new { id = vm.Task.ModuleId });
        }

        [RoleAuthorize(UserType = AppUserType.Lecturer)]
        public ActionResult Delete(string taskId)
        {
            dbRepo.DeleteTask(Convert.ToInt32(taskId));
            return RedirectToAction("Index", "Home");
        }
    }
}

Fomka-Web-App/fomka-web/Views/Tasks/Add.cshtml
@model fomka_web.Models.TaskVm
@{
    ViewBag.Title = "Add Task";
}

<h2>Додати завдання</h2>
<div class="content">
    @using (Html.BeginForm("AddTask", "Tasks", FormMethod.Post))
    {
        @Html.HiddenFor(m=>m.Task.Id)
        <div class="form-group">
            @Html.LabelFor(m => m.Task.Title)
            @Html.TextBoxFor(m => m.Task.Title, new { @class = "form-control" })
            @Html.Label("lab", "Description")
            @Html.TextAreaFor(m => m.Task.Description, new { @class = "form-control", @rows = "4"})
        </div>
        <div class="container">
            <div class="row">
                <div class="col-sm6 form-group">
                    @Html.LabelFor(m => m.ProgrammingLanguages)
                    @Html.DropDownListFor(m => m.Task.PLId, Model.ProgrammingLanguages, new { @class = "form-control" })
                </div>
                <div class="col-sm6 form-group">
                    @Html.LabelFor(m => m.DifficultyLevels)
                    @Html.DropDownListFor(m => m.Task.DifficultyLevelId, Model.DifficultyLevels, new { @class = "form-control" })
                </div>
                <div class="col-sm6 form-group">
                    @Html.LabelFor(m => m.Modules)
                    @Html.DropDownListFor(m => m.Task.ModuleId, Model.Modules, new { @class = "form-control" })
                </div>
            </div>
        </div>
        <div>

            @Html.LabelFor(m => m.Task.Standard.StandardFile)
            @Html.TextAreaFor(m => m.Task.Standard.StandardFile, new { @class = "form-control", @rows = "10", @cols = "50" })

        </div>
        <br/>
        <div class="col-lg-4">
            <div class="row mg2">
                <input type="submit" class="btn btn-primary" value="Зберегти"/>
                <a href="../Home/Index" class="btn btn-default">Відмінити</a>
            </div>
            
        </div>
        
                                                                     
    }
</div>

Fomka-Web-App/fomka-web/Views/Tasks/Edit.cshtml
@model fomka_web.Models.TaskVm
@{
    ViewBag.Title = "Edit Task";
}

<h2>Редагувати завдання</h2>
<div class="content">
    @using (Html.BeginForm("EditTask", "Tasks", FormMethod.Post))
    {
        @Html.HiddenFor(m=>m.Task.Id)
        <div class="form-group">
            @Html.LabelFor(m => m.Task.Title)
            @Html.TextBoxFor(m => m.Task.Title, new { @class = "form-control" })
            @Html.Label("lab", "Description")
            @Html.TextAreaFor(m => m.Task.Description, new { @class = "form-control", @rows = "4"})
        </div>
        <div class="container">
            <div class="row">
                <div class="col-sm6 form-group">
                    @Html.LabelFor(m => m.ProgrammingLanguages)
                    @Html.DropDownListFor(m => m.Task.PLId, Model.ProgrammingLanguages, new { @class = "form-control" })
                </div>
                <div class="col-sm6 form-group">
                    @Html.LabelFor(m => m.DifficultyLevels)
                    @Html.DropDownListFor(m => m.Task.DifficultyLevelId, Model.DifficultyLevels, new { @class = "form-control" })
                </div>
            </div>
            </div>
        <div>

            @Html.LabelFor(m => m.Task.Standard.StandardFile)
            @Html.TextAreaFor(m => m.Task.Standard.StandardFile, new { @class = "form-control", @rows = "10", @cols = "50" })

        </div>
        <br/>
        <div class="col-lg-4">
            <div class="row mg2">
                <input type="submit" class="btn btn-primary" value="Зберегти"/>
                <a href="../Home/Index" class="btn btn-default">Відмінити</a>
            </div>
            
        </div>
        
                                                                     
    }
</div>

Fomka-Web-App/fomka-web/Views/Tasks/Open.cshtml
@model fomka_web.Models.TaskVm
@{
    ViewBag.Title = "Task";
}

<h2>Task #@Model.Task.Id</h2>

<div class="row">
    <div class="col-lg-2">
        <div class="row">
            <h3>Завдання</h3>
        </div>
        <div class="row">
            <h4>@Model.Task.Title</h4>
        </div>
        <br />
        <div class="row">
            <p>Мова програмування @Model.Task.ProgrammingLanguage.Title</p>
        </div>
        <div class="row">
            <h3>Опис завдання</h3>
        </div>
        <div class="row">
            <p>@Model.Task.Description</p>
        </div>
        <div class="row">
            <!-- Button trigger modal -->
            <button type="button" class="btn btn-primary" data-toggle="modal" data-target="#confirmationModal">
                Здати завдання
            </button>
        </div>
    </div>
    <div class="col-lg-5">
        <h4>Розставте блоки в правильному порядку</h4>
        @foreach (var block in Model.SelectedBlocks)
        {
            <div class="card">
                <div class="card-body">
                    <div class="row mg-2">
                        <a class="btn btn-danger removeBlock codeblock" onclick="remove(@block.BlockID,this)">
                            <pre>@block.Code</pre>
                        </a>
                    </div>
                </div>
            </div>
        }
    </div>
    <div class="col-lg-5">
        <h4>Доступні блоки:</h4>
        @foreach (var block in Model.SequenceOfBlocks)
        {
            if (!block.selected)
            {
                <div class="card">
                    <div class="card-body">
                        <div class="row mg-2">
                            <a class="btn btn-success addBlock codeblock" value="Add" onclick="add(@block.BlockID, this)">
                                <pre>@block.Code</pre>
                            </a>
                        </div>
                    </div>
                </div>
            }
        }
        @Html.HiddenFor(m => m.Task.Id, new { @id = "taskId" })
        @Html.HiddenFor(m => m.selection, new { @id = "selection" })
        @Html.HiddenFor(m => m.blocks, new { @id = "blocks" })

    </div>
</div>

@using (Html.BeginForm("Submit", "Tasks", FormMethod.Post))
{
    <div class="modal fade" id="confirmationModal" tabindex="-1" role="dialog" aria-hidden="true">
        <div class="modal-dialog" role="document">
            <div class="modal-content">
                <div class="modal-header">
                    <div class="row">
                        <div class="col col-sm-6">
                            <h3 class="modal-title">Завдання: @Model.Task.Title</h3>
                        </div>
                        <div class="col" style="padding: 10px; padding-right: 20px;">
                            <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                                <span aria-hidden="true">&times;</span>
                            </button>
                        </div>
                    </div>
                </div>
                <div class="modal-body">
                    <p>Бажаєте завершити завдання і здати на оцінювання?</p>
                </div>
                <div class="modal-footer">
                    <div class="row" style="padding-right: 20px">
                        @Html.HiddenFor(m => m.Task.Id)
                        <input type="submit" class="btn btn-primary" value="Здати"/>
                        <button type="button" class="btn btn-secondary" data-dismiss="modal">Відміна</button>
                    </div>
                </div>
            </div>
        </div>
    </div>
}

<script type="text/javascript" src="~/Scripts/Tasks.js"></script>
<script type="text/javascript" src="~/Scripts/jsCookie.js"></script>

Fomka-Web-App/fomka-web/Views/Tasks/Submit.cshtml
@model fomka_web.Models.TaskVm
@{
    ViewBag.Title = "Submit";
}

<h2>@Model.Answer</h2>
<div class="row">
    <a class="btn btn-primary" href="~/Home/Index">Продовжити</a>
</div>

<script type="text/javascript" src="~/Scripts/CoockieCleaner.js"></script>

Fomka-Web-App/fomka-web/Views/Tasks/index.cshtml
@model fomka_web.Models.TaskVm
@{
    ViewBag.Title = "Task";
}